[package]
name = "dylmarriner/creature-empire"
description = "Creature Empire Roblox game"
version = "0.1.0"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
private = true

[dependencies]

[server-dependencies]

[dev-dependencies]
